################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_n.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/assign_variable.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_args.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_to.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/call_once.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cast.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ceil.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cumsum.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depth_to_space.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/div.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elu.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/exp.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/expand_dims.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fill.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_div.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_mod.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather_nd.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/if.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/log_softmax.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/lstm_eval.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mirror_pad.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mul_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/neg.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pack.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pad.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pooling_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/read_variable.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reshape.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/round.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/shape.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/slice.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_depth.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split_v.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squared_difference.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/tanh.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unpack.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/var_handle.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/while.cc \
../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_n.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/assign_variable.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_args.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_to.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/call_once.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cast.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ceil.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cumsum.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depth_to_space.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/div.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elu.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/exp.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/expand_dims.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fill.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_div.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_mod.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather_nd.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/if.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/log_softmax.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/lstm_eval.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mirror_pad.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mul_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/neg.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pack.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pad.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pooling_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/read_variable.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reshape.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_bilinear.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/round.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/shape.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/slice.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_depth.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split_v.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squared_difference.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/tanh.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unpack.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/var_handle.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/while.d \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_n.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/assign_variable.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_args.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_to.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/call_once.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cast.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ceil.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cumsum.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depth_to_space.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/div.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elu.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/exp.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/expand_dims.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fill.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_div.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_mod.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather_nd.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/if.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/log_softmax.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/lstm_eval.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mirror_pad.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mul_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/neg.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pack.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pad.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pooling_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/read_variable.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reshape.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_bilinear.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/round.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/shape.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/slice.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_depth.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split_v.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squared_difference.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/tanh.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unpack.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/var_handle.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/while.o \
./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/%.o Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/%.su: ../Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/%.cc Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L475xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-tensorflow_lite-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-Drivers-2f-tensorflow_lite-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/activations_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_n.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_n.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/add_n.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/assign_variable.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/assign_variable.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/assign_variable.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_args.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_args.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_args.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_to.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_to.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/broadcast_to.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/call_once.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/call_once.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/call_once.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cast.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cast.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cast.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ceil.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ceil.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ceil.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cumsum.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cumsum.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/cumsum.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depth_to_space.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depth_to_space.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depth_to_space.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/dequantize_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/div.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/div.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/div.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.su
	-$(RM) ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elu.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elu.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/elu.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/exp.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/exp.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/exp.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/expand_dims.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/expand_dims.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/expand_dims.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fill.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fill.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fill.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_div.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_div.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_div.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_mod.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_mod.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/floor_mod.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather_nd.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather_nd.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/gather_nd.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/if.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/if.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/if.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2_pool_2d.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2_pool_2d.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2_pool_2d.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/leaky_relu_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/log_softmax.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/log_softmax.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/log_softmax.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logical_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/logistic_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/lstm_eval.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/lstm_eval.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/lstm_eval.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/micro_tensor_utils.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mirror_pad.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mirror_pad.o
	-$(RM) ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mirror_pad.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mul_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mul_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/mul_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/neg.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/neg.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/neg.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pack.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pack.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pack.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pad.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pad.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pad.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pooling_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pooling_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/pooling_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/prelu_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/read_variable.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/read_variable.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/read_variable.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reduce_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reshape.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reshape.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/reshape.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_bilinear.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_bilinear.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_bilinear.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/round.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/round.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/round.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/shape.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/shape.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/shape.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/slice.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/slice.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/slice.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_depth.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_depth.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/space_to_depth.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split_v.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split_v.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/split_v.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squared_difference.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squared_difference.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squared_difference.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub_common.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/sub_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.d
	-$(RM) ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/tanh.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/tanh.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/tanh.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unpack.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unpack.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/unpack.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/var_handle.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/var_handle.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/var_handle.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/while.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/while.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/while.su ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.d ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.o ./Drivers/tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-Drivers-2f-tensorflow_lite-2f-tensorflow-2f-lite-2f-micro-2f-kernels

