void __attribute__ ((noinline))  pulp_nn_add_u8_u8 (
  uint8_t * Im_in_1,             // pointer to the input feature map1
  uint8_t * Im_in_2,             // pointer to the input feature map2
  uint16_t  ch_im_in,          // number of channels of the IFM
  uint16_t  dim_im_in_h,      
  uint16_t  dim_im_in_w,
  uint8_t * Im_out,            // pointer to the output
  uint16_t out_mult1,            // paramter to requantize
  uint16_t out_mult2,            // paramter to requantize
  uint16_t out_shift            // paramter to requantize
);

void pulp_nn_avgpool_u8 (
  uint8_t *  Im_in,
  uint16_t  dim_im_in_x,
  uint16_t  dim_im_in_y,
  uint16_t  ch_im_in,
  uint16_t  dim_kernel_x,
  uint16_t  dim_kernel_y,
  uint16_t  padding,
  uint16_t  stride,
  uint16_t  dim_im_out_x,
  uint16_t  dim_im_out_y,
  int8_t *  bufferA,
  uint8_t *  Im_out,
  int32_t * pOutBufferAcc,
  int8_t    flag_acc_buff_out,
  int8_t    flag_first_ch_out,
  int       flag_relu,
  const uint16_t  out_shift,
  const uint16_t  out_mult
);

void pulp_nn_maxpool_u8 (
  uint8_t * Im_in,             // pointer to the input feature map
  uint16_t  dim_im_in_x,       // spatial dimension of the input feature map
  uint16_t  dim_im_in_y,
  uint16_t  ch_im_in,          // number of channels of the IFM
  uint16_t  dim_kernel,        // spatial dimension of the pooling filter
  uint16_t  padding_t,           // amount of padding
  uint16_t  padding_b,           // amount of padding
  uint16_t  padding_l,           // amount of padding
  uint16_t  padding_r,           // amount of padding
  uint16_t  stride,            // amount of stride
  uint16_t  dim_im_out_x,      // reduced spatial dimension of output
  uint16_t  dim_im_out_y,
  int8_t *  bufferA,           // actually not used in this fx
  uint8_t * Im_out,            // pointer to the output
  int32_t * pOutBufferAcc,
  int8_t    flag_acc_buff_out,
  int8_t    flag_first_ch_out
);

// void pulp_nn_linear_i8_u8 (
//         uint8_t * pIn,
//         int32_t * pInBufferAcc,
//         int8_t *  pWeights,
//         uint16_t  dim_vec,
//         uint16_t  num_o_neurons,
//         uint16_t  bias_shift,
//         uint16_t  out_shift,
//         int8_t *  bias,
//         uint8_t * pOut,
//         int32_t * pOutBufferAcc,
//         uint8_t   displacement,
//         int       flag_clip,
//         int       flag_displacement
// );



void pulp_nn_conv_u8_u8_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u8_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u8_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u4_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u4_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u4_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u2_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u2_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u8_u2_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u8_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u8_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u8_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u4_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u4_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u4_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u2_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u2_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u4_u2_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u8_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u8_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u8_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u4_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u4_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u4_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u2_i8(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u2_i4(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_conv_u2_u2_i2(
          const uint8_t *pInBuffer,
    const uint16_t dim_in_x,
       const uint16_t dim_in_y,
    const uint16_t ch_in,
    const int8_t *pWeight,
    const uint16_t ch_out,
    const uint16_t dim_kernel_x,
    const uint16_t dim_kernel_y,
    const uint16_t padding_y_top,
    const uint16_t padding_y_bottom,
    const uint16_t padding_x_left,
    const uint16_t padding_x_right,
    const uint16_t stride_x,
    const uint16_t stride_y,
    const int8_t *bias,
    const uint16_t bias_shift,
    const int8_t out_shift,
    const uint16_t out_mult,
          uint8_t *pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
    int64_t *k,
    int64_t *lambda,
    uint8_t *pIm2ColBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


int8_t *pulp_nn_matmul_u8_i8(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u8_i4(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u8_i2(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u4_i8(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u4_i4(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u4_i2(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u2_i8(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u2_i4(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


int8_t *pulp_nn_matmul_u2_i2(
          const int8_t * pWeight,
          uint8_t * pInBuffer,
          uint16_t ch_out,
          uint16_t num_col_im2col,
    uint16_t bias_shift,
    int8_t out_shift,
          uint16_t out_mult,
          int64_t *k,
          int64_t *lambda, 
    const int8_t * bias,
          uint8_t * pOut,
          int flag_relu,
          int flag_batch_norm);


void pulp_nn_dw_u8_u8_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u8_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u8_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u4_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u4_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u4_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u2_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u2_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u8_u2_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u8_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u8_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u8_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u4_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u4_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u4_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u2_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u2_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u4_u2_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u8_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u8_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u8_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u4_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u4_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u4_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u2_i8(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u2_i4(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_dw_u2_u2_i2(
          const uint8_t * pInBuffer,
          const uint16_t dim_in_x,
          const uint16_t dim_in_y,
          const uint16_t ch_in,
          const int8_t * pWeightBuffer,
          const uint16_t ch_out,
          const uint16_t dim_kernel_x,
          const uint16_t dim_kernel_y,
          const uint16_t padding_y_top,
          const uint16_t padding_y_bottom,
          const uint16_t padding_x_left,
          const uint16_t padding_x_right,
          const uint16_t stride_x,
          const uint16_t stride_y,
          const int8_t * bias,
          const uint16_t bias_shift,
          const int8_t out_shift,
          const uint16_t out_mult,
          uint8_t * pOutBuffer,
          const uint16_t dim_out_x,
          const uint16_t dim_out_y,
          int64_t * k,
          int64_t * lambda,
          uint8_t * pIm2ColBuffer,
          int8_t * pWtBuffer,
          int flag_relu,
          int flag_batch_norm,
          unsigned int * memory_chan);


void pulp_nn_linear_u8_i32_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i32_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i32_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i32_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i32_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i32_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i32_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i32_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i32_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i8_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i8_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i8_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i4_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i4_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i4_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i2_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i2_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u8_i2_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i8_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i8_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i8_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i4_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i4_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i4_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i2_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i2_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u4_i2_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i8_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i8_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i8_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i4_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i4_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i4_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i2_i8(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i2_i4(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );


void pulp_nn_linear_u2_i2_i2(
               uint8_t *pInBuffer,
               int8_t *pWeights,
               uint16_t dim_vec,
               uint16_t num_o_neurons,
               int8_t *bias,
               uint16_t bias_shift,
               int8_t out_shift,
               uint16_t out_mult,
               int64_t *k,
               int64_t *lambda,
               int32_t *pOutBuffer,
               int flag_relu,
               int flag_batch_norm,
               unsigned int * memory_chan
               );
